name: Keep Render Alive

on:
  schedule:
    - cron: "*/5 * * * *"   # Run every 5 minutes
  workflow_dispatch:          # Allow manual trigger

jobs:
  keep_alive_job:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Production
        run: |
          echo "Pinging Production..."
          curl -s -o /dev/null -w "%{http_code}\n" https://e-commerce-be-citd.onrender.com/health

      - name: Ping Staging
        run: |
          echo "Pinging Staging..."
          curl -s -o /dev/null -w "%{http_code}\n" https://e-commerce-be-citd-staging.onrender.com/health
