name: Keep Render Alive

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes
  workflow_dispatch:        # allow manual trigger

jobs:
  keep_alive_job:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render Health Endpoint
        run: |
          echo "Pinging Render..."
          curl -s -o /dev/null -w "%{http_code}\n" https://e-commerce-be-citd.onrender.com/health
